-- CreateTable
CREATE TABLE "WLB_CUENTA" (
    "CUEId" SERIAL NOT NULL,
    "CUENombre" TEXT NOT NULL,
    "CUETipo" TEXT NOT NULL,
    "CUESaldoInicial" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "CUEActiva" BOOLEAN NOT NULL DEFAULT true,
    "CUECreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USUId" INTEGER NOT NULL,

    CONSTRAINT "WLB_CUENTA_pkey" PRIMARY KEY ("CUEId")
);

-- CreateTable
CREATE TABLE "WLB_CATEGORIA" (
    "CATId" SERIAL NOT NULL,
    "CATNombre" TEXT NOT NULL,
    "CATTipo" TEXT NOT NULL,
    "CATColor" TEXT,
    "CATIcono" TEXT,
    "CATActiva" BOOLEAN NOT NULL DEFAULT true,
    "CATCreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USUId" INTEGER NOT NULL,

    CONSTRAINT "WLB_CATEGORIA_pkey" PRIMARY KEY ("CATId")
);

-- CreateTable
CREATE TABLE "WLB_MOVIMIENTO" (
    "MOVId" SERIAL NOT NULL,
    "MOVTipo" TEXT NOT NULL,
    "MOVMonto" DECIMAL(65,30) NOT NULL,
    "MOVDescripcion" TEXT,
    "MOVFecha" TIMESTAMP(3) NOT NULL,
    "MOVActiva" BOOLEAN NOT NULL DEFAULT true,
    "MOVCreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USUId" INTEGER NOT NULL,
    "CUEId" INTEGER NOT NULL,
    "CATId" INTEGER,

    CONSTRAINT "WLB_MOVIMIENTO_pkey" PRIMARY KEY ("MOVId")
);

-- CreateTable
CREATE TABLE "WLB_META" (
    "METId" SERIAL NOT NULL,
    "METNombre" TEXT NOT NULL,
    "METDescripcion" TEXT,
    "METMontoObjetivo" DECIMAL(65,30) NOT NULL,
    "METMontoActual" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "METFechaObjetivo" TIMESTAMP(3),
    "METActiva" BOOLEAN NOT NULL DEFAULT true,
    "METCreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USUId" INTEGER NOT NULL,

    CONSTRAINT "WLB_META_pkey" PRIMARY KEY ("METId")
);

-- CreateTable
CREATE TABLE "WLB_PRESUPUESTO_MENSUAL" (
    "PREId" SERIAL NOT NULL,
    "PREAnio" INTEGER NOT NULL,
    "PREMes" INTEGER NOT NULL,
    "PREMonto" DECIMAL(65,30) NOT NULL,
    "PRECreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USUId" INTEGER NOT NULL,
    "CATId" INTEGER NOT NULL,

    CONSTRAINT "WLB_PRESUPUESTO_MENSUAL_pkey" PRIMARY KEY ("PREId")
);

-- AddForeignKey
ALTER TABLE "WLB_CUENTA" ADD CONSTRAINT "WLB_CUENTA_USUId_fkey" FOREIGN KEY ("USUId") REFERENCES "WLB_USUARIO"("USUId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_CATEGORIA" ADD CONSTRAINT "WLB_CATEGORIA_USUId_fkey" FOREIGN KEY ("USUId") REFERENCES "WLB_USUARIO"("USUId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_MOVIMIENTO" ADD CONSTRAINT "WLB_MOVIMIENTO_USUId_fkey" FOREIGN KEY ("USUId") REFERENCES "WLB_USUARIO"("USUId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_MOVIMIENTO" ADD CONSTRAINT "WLB_MOVIMIENTO_CUEId_fkey" FOREIGN KEY ("CUEId") REFERENCES "WLB_CUENTA"("CUEId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_MOVIMIENTO" ADD CONSTRAINT "WLB_MOVIMIENTO_CATId_fkey" FOREIGN KEY ("CATId") REFERENCES "WLB_CATEGORIA"("CATId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_META" ADD CONSTRAINT "WLB_META_USUId_fkey" FOREIGN KEY ("USUId") REFERENCES "WLB_USUARIO"("USUId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_PRESUPUESTO_MENSUAL" ADD CONSTRAINT "WLB_PRESUPUESTO_MENSUAL_USUId_fkey" FOREIGN KEY ("USUId") REFERENCES "WLB_USUARIO"("USUId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WLB_PRESUPUESTO_MENSUAL" ADD CONSTRAINT "WLB_PRESUPUESTO_MENSUAL_CATId_fkey" FOREIGN KEY ("CATId") REFERENCES "WLB_CATEGORIA"("CATId") ON DELETE RESTRICT ON UPDATE CASCADE;
