-- CreateTable
CREATE TABLE "WLB_USUARIO" (
    "USUId" SERIAL NOT NULL,
    "USUNombre" TEXT NOT NULL,
    "USUCorreo" TEXT NOT NULL,
    "USUPassword" TEXT NOT NULL,
    "USUCreadoEn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WLB_USUARIO_pkey" PRIMARY KEY ("USUId")
);

-- CreateIndex
CREATE UNIQUE INDEX "WLB_USUARIO_USUCorreo_key" ON "WLB_USUARIO"("USUCorreo");
